function [waveform, transmitter, receiver, radiator, collector] = config_radar_system_isotrope()
    % CONFIG_RADAR_SYSTEM - Version ISOTROPE 
    
    % 1. Paramètres Système
    fc = 11e9;                           
    
    % 2. Le Signal
    bw = 5e6;              
    fs = 2 * bw;  % critère Shannon-Nyquist => pas de repliage lors de l'échantillonage (analogique -> numérique)          
    pulse_width = 100e-6;  % s | durée d'une émission
    prf = 5000;   % Hz | 1/prf = PRI => durée entre deux débuts d'émissions      
    
    waveform = phased.LinearFMWaveform(...
        'SampleRate', fs, ...
        'PulseWidth', pulse_width, ...
        'PRF', prf, ...
        'OutputFormat', 'Pulses', ...
        'NumPulses', 64);   % NumPulses d'émissions à la suite : Tint = NumPulses * PRI => durée où l'on suppose vitesse constante

    % 3. Antenne : Isotrope
    
    antenna = phased.IsotropicAntennaElement(...
        'FrequencyRange', [8e9 12e9]);
    
    % 4. L'Émetteur (Satellite)
    peak_power = 1000;     
    gain_tx    = 30;       
    
    transmitter = phased.Transmitter(...
        'PeakPower', peak_power, ...
        'Gain', gain_tx, ...
        'InUseOutputPort', true); 
        
    radiator = phased.Radiator(...
        'Sensor', antenna, ...
        'OperatingFrequency', fc);

    % 5. Le Récepteur (Station Sol)
    noise_fig = 2;         
    gain_rx   = 40;        
    
    receiver = phased.ReceiverPreamp(...
        'Gain', gain_rx, ...
        'NoiseFigure', noise_fig, ...
        'SampleRate', fs); 
        
    collector = phased.Collector(...
        'Sensor', antenna, ...
        'OperatingFrequency', fc);
        
    disp('Système RF configuré (Antenne Isotrope).');
end